### ISSUE TITLE
feat: Add some tls options

### ISSUE THREAD

**Issue by boggyhole** [nakabonne/ali#103]
To i.e. allow mutual tls, adding root certificates and to allow for tls verification

**Comment by boggyhole** [comment]
see #104

**Comment by nakabonne** [comment]
@boggyhole A new version [v0.6.1](https://github.com/nakabonne/ali/releases/tag/v0.6.1) got released including this patch. Thank you!

**Comment by boggyhole** [comment]
@nakabonne Great, thanks for the quick response on this!

**Comment by nakabonne** [comment]
@boggyhole Thank YOU for your contribution!
