### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by fedorlitau** [nakabonne/ali#111]
A very seldomly occurring bug (race condition):

![image](https://user-images.githubusercontent.com/83718336/131556805-cfe9304f-adc6-4092-88e7-c23c8f3ce234.png)

The code in `drawer.go:202` looks like:

![image](https://user-images.githubusercontent.com/83718336/131556902-1362611e-66a4-420f-8e09-19c68bab12dd.png)

`m.StatusCodes` is coming from the [tsenart/vegeta](https://github.com/tsenart/vegeta) library:

![image](https://user-images.githubusercontent.com/83718336/131557101-7a5804c2-3b55-45da-8ee4-076e03d2f9c0.png)

There, the modification of the map happens:

![image](https://user-images.githubusercontent.com/83718336/131557140-57e4f254-3c26-4c65-8ae1-e20b5e33abea.png)

This needs some rework - maybe not use the actual map from `vegeta`? Unfortunately I do not know your codebase well enough to propose a solution =)

BTW very nice tool! ;-)

Best
Fedor

**Comment by fedorlitau** [comment]
The workaround in PR #112 seems to help:

![image](https://user-images.githubusercontent.com/83718336/131633750-d43a65eb-487f-4385-97d4-483b75e69362.png)

ali now running for 40 hours -- before the error happened after a couple of minutes for me

**Comment by nakabonne** [comment]
@fedorlitau Good catch! Let me take a look from now.
