### ISSUE TITLE
Requestparameter as cli options

### ISSUE THREAD

**Issue by AndreasHerold** [nakabonne/ali#20]
Hey,

please add the feature to add cli options for the http(s) requests like
`ali --targeturl=http://www.foo.bar --duration=10 --timeout=30 `
an so on.
Thank you.

**Comment by nakabonne** [comment]
@AndreasHerold Hey, thanks for your suggestion! Yup, you have a point, I'm feeling the same way. I feel setting with the input fields to be difficult to use, so I put it in the roadmap to only support input through flags (updated README just now).

**Comment by AndreasHerold** [comment]
@nakabonne Thank you for your feedback.
To make things easier I think it is better to you the JSONTargeter instead of the StaticTargeter. With that you just have to pass a file with all the request parameters (method, header, url, body).
Or you provide both methods.
Maybe I can implement it by myself later this week.

**Comment by nakabonne** [comment]
It would be a nice idea to give the request params by passing a file. Seems better to add support for both ways.

I'm now implementing the CLI options support, so please wait until it is completed ;)

**Comment by nakabonne** [comment]
@AndreasHerold Hey, cli options are now available at [v0.3.0](https://github.com/nakabonne/ali/releases/tag/v0.3.0)! It would be nice if you could try it.

**Comment by AndreasHerold** [comment]
Hey @nakabonne thank you for your work. Works finde except from time to time there is a crash but unfortunatly I'm not able to fetch the stack trace because my shell breaks too :-(
The only way for me is to send you a screenshot
![image](https://user-images.githubusercontent.com/8049475/94929309-33db2380-04c5-11eb-8013-25f19aead7f7.png)

**Comment by nakabonne** [comment]
@AndreasHerold Thanks for reporting! Could you please open a new issue with the screenshot and the way to repro it?

**Comment by nakabonne** [comment]
Closing since cli options are now supported.
