### ISSUE TITLE
Concurrent requests

### ISSUE THREAD

**Issue by fkfgq2008** [nakabonne/ali#21]
Excuse me?

How does this tool test 500 concurrent requests for URLs? You need to look at those parameters

**Comment by nakabonne** [comment]
@fkfgq2008 Hi, It's not possible to fix the number of workers running in concurrent. Instead in the near future, it will be able to specify the initial number of workers and the maximum number of workers (https://github.com/nakabonne/ali/issues/1).

**Comment by nakabonne** [comment]
Closing since this can be resolved by https://github.com/nakabonne/ali/issues/1. Feel free to re-open it if you have any other questions.
