### ISSUE TITLE
Support keepalive options

### ISSUE THREAD

**Issue by nakabonne** [nakabonne/ali#30]
- [ ] Enable to switch to use persistent connections

Only tiny changes are required because all we have to do is just pass to the Vegeta API.

**Comment by cvhariharan** [comment]
Hi, I can pick this up if this is still open :smile:

**Comment by nakabonne** [comment]
@cvhariharan Hi, glad you're interested in it! That would be nice, look forward to your PR.

**Comment by nakabonne** [comment]
Closing since this is resolved by #43
