### ISSUE TITLE
modify others text for better reading 

### ISSUE THREAD

**Issue by brenol** [nakabonne/ali#33]
This is actually a question.

Perhaps Earliest/Latest/End shouldn't use String() for a time.Time. It gets noisy when you have a timezone (because of Monotonic): 
![image](https://user-images.githubusercontent.com/7342697/94883416-00ef4c00-0441-11eb-832d-204c0f9be904.png)

Perhaps we can use time.RFC3339Nano?

![image](https://user-images.githubusercontent.com/7342697/94884076-d2727080-0442-11eb-9fb1-22bc8515d47b.png)

Or some middleground, without the T:
![image](https://user-images.githubusercontent.com/7342697/94884146-0352a580-0443-11eb-9f36-783caf9d3333.png)

Or without millis/nanos:
![image](https://user-images.githubusercontent.com/7342697/94884363-9ee41600-0443-11eb-89f5-84fb0d64ee56.png)

Or without millis/nanos and aligned:
![image](https://user-images.githubusercontent.com/7342697/94884392-ba4f2100-0443-11eb-98e5-5af3d08d4bb0.png)

Or with millis/nanos, aligned, without monotonic:
![image](https://user-images.githubusercontent.com/7342697/94884518-13b75000-0444-11eb-87f7-4d0c1ad0f507.png)

And (I know I'm talking mostly about date but...) with everything aligned:
![image](https://user-images.githubusercontent.com/7342697/94884632-655fda80-0444-11eb-94e7-37ad2fc455f1.png)

**Comment by brenol** [comment]
We can also remove the timezone. The user probably knows the timezone they are in? (unless they are running in a server...)

**Comment by nakabonne** [comment]
@brenol Thanks for the suggestion, this is actually the problem that I've put off in the long-term.

The pattern without `millis/nanos` looks good. And I also think every field should be aligned.

**Comment by nakabonne** [comment]
It would be great if you work on it and open a PR ;)
