### ISSUE TITLE
zoom: undo with right click?

### ISSUE THREAD

**Issue by brenol** [nakabonne/ali#34]
Took me sometime to notice we can undo a Zoom with the mouse scroll (why? Not sure. Perhaps documentation in the README will do), but I thought that we can simulate zoom-outs with a mouse right click.

Does it make sense to you? (Zoom in with selection; zoom out with right click)

**Comment by nakabonne** [comment]
@brenol Sorry, I know currently mousing documents are missing. You can undo the zoomed chart by scrolling down. And I'd say we cannot undo it with right-click due to the limitations of [termdash](https://github.com/mum4k/termdash).

**Comment by brenol** [comment]
Actually, we can:
```go

func mousebinds(ctx context.Context, cancel context.CancelFunc, dr *drawer, targetURL string, opts attacker.Options) func(*terminalapi.Mouse) {
	return func(m *terminalapi.Mouse) {
		switch m.Button {
		case mouse.ButtonRight: // zoom out
			// fake a zoom out, with the current X & Y
			dr.widgets.latencyChart.Mouse(&terminalapi.Mouse{
				Position: m.Position,
				Button:   mouse.ButtonWheelDown,
			})
		}
	}
}
```

It's not perfect, but it can work...

**Comment by nakabonne** [comment]
Wow, you're right, I wasn't sure that! But to be honest, I don't want to make it as complicated as possible. I'd say it's enough to undo with scrolling down.

**Comment by brenol** [comment]
Np, I'll close this one then :)
