### ISSUE TITLE
"high" CPU usage while idle

### ISSUE THREAD

**Issue by brenol** [nakabonne/ali#35]
it's using 20% CPU while idle here (because of termdash.RedrawInterval).

Perhaps we can use termdash.NewController and only redraw after 250ms, while its running (this will probably bring a lot of complexity?)?

**Comment by nakabonne** [comment]
I'd say what RedrawInterval is being constant is a problem as well. To make it changeable, I'm considering to support the `--redraw-interval` option.

**Comment by nakabonne** [comment]
I just opened an issue about it https://github.com/nakabonne/ali/issues/39

**Comment by nakabonne** [comment]
The next release includes `--redraw-interval`. Please use it to prevent CPU from high usage.
