### ISSUE TITLE
Support local address option

### ISSUE THREAD

**Issue by nakabonne** [nakabonne/ali#50]
- [ ] Make it possible to specify the local address used with the requests by passing `--local-addr`

Only tiny changes are required because all we have to do is just pass to the Vegeta API.

**Comment by shubham14bajpai** [comment]
@nakabonne This also requires similar changes? If possible you can list all the required flags and I would like to work on all of them in a single PR.

**Comment by nakabonne** [comment]
@shubham14bajpai Sure, all of them need similar changes. But to be honest, I haven't been able to determine what options to support accurately yet.

**Comment by nakabonne** [comment]
This is resolved by #54
