### ISSUE TITLE
Vegeta causes panic at high rates

### ISSUE THREAD

**Issue by nakabonne** [nakabonne/ali#57]
Run the following:
```
ali -r 1000 http://host.xz
```

Then panic occurred.
The noteworthy stack traces are:
- tsenart/vegeta/v12/lib/attack.go:340
- tsenart/vegeta/v12/lib/attack.go:312

![image](https://user-images.githubusercontent.com/19730728/95535815-5967b000-0a24-11eb-9525-f6cd9791614b.png)

**Comment by jackey925** [comment]
It happened to me, too
How to solve that problem

**Comment by nakabonne** [comment]
@jackey925 Hey, this is resolved by https://github.com/nakabonne/ali/pull/60. And you can gain the revised version from [v0.4.0](https://github.com/nakabonne/ali/releases/tag/v0.4.0)!
