### ISSUE TITLE
Invisible text in WSL2

### ISSUE THREAD

**Issue by amalshaji** [nakabonne/ali#6]
I can type, but the text is invisible 

![notext](https://user-images.githubusercontent.com/18011385/93732110-78c1a900-fbed-11ea-8d30-464838958c9f.PNG)

**Comment by nakabonne** [comment]
@amalshaji Hi, thanks for reporting! If your terminal size less than a certain amount of cells, it wouldn't be drawn until the terminal size increases. Would it be possible to stretch your terminal vertically?

**Comment by amalshaji** [comment]
Yup. Working on a full screen.

**Comment by nakabonne** [comment]
Glad to hear that.
