### ISSUE TITLE
Add support for basic auth?

### ISSUE THREAD

**Issue by erikbos** [nakabonne/ali#65]
Fun tool! It would be great if http basic auth would be supported via cli as well

**Comment by nakabonne** [comment]
@erikbos Hi, thank you for your interest! You can use the `-H` option to set HTTP headers.
```
$ echo -n 'user:pass' | base64
dXNlcjpwYXNz
$ ali -H "Authorization:Basic dXNlcjpwYXNz" http://host.xz
```

**Comment by erikbos** [comment]
Indeed that works..  just saying that something like `-u user:passwd` would be nice to have. Yes, I am lazy :-)

**Comment by brenol** [comment]
@erikbos you can also use this way (which also works on browsers!):

```sh
ali  http://myuser:mypassword@host.xz
```

**Comment by nakabonne** [comment]
@brenol Thanks. Yeah, I'll add a couple of examples for various kinds of use cases in the near future.
