### ISSUE TITLE
fix issue with percentiles chart navigation

### ISSUE THREAD

**Issue by brenol** [nakabonne/ali#70]
OK, so this one is actually weird.

From the point of view of `code`, the current implementation is correct.

From the point of view of usability, though, it's incorrect.

As the first chart in ali is `latencyChart`, pressing `L` the first time does not change to the next chart, which is percentiles.
This problem does not happen with backwards button (H), and is easily fixed with changing start position to 0 (which is a fact).

I'm finishing a PR that will fix this problem.

**Comment by nakabonne** [comment]
resolved by https://github.com/nakabonne/ali/pull/71
