### ISSUE TITLE
Natively support specifying HTTP proxies

### ISSUE THREAD

**Issue by hazcod** [nakabonne/ali#94]
I've had very mixed results for some reason specifying the environment variable `HTTP_PROXY` to Ali.
Not sure if this is related, but it would be nice to natively support supplying a proxy via an argument.

e.g. curl uses `-x`.

**Comment by nakabonne** [comment]
@hazcod Hi, thank you for reporting. I'm aware that `net/http.Client` automatically switches to use the given proxy if you set the `HTTP_PROXY` environment variable, but I might be wrong. Could you tell me a little bit more about what mixed results you've had?

**Comment by hazcod** [comment]
I'll close this for now since it seems to work reliably with a system environment variable, but not when I declare it in a process way:

```shell
# sometimes works
% HTTP_PROXY="http://127.0.0.1:8080" ali https://google.com/

# always works
% docker run --rm -ti -e 'HTTP_PROXY=http://127.0.0.1:8080' nakabonne/ali ali https://google.com/
```

**Comment by nakabonne** [comment]
@hazcod Hmm, interesting. Okay, feel free to open it when needed 👍
