### ISSUE TITLE
Scrolling Issue on Info Boxes at Bottom

### ISSUE THREAD

**Issue by lordlycastle** [nakabonne/ali#95]
I ran some tests and the results are too large for the bottom boxes to appear. However the scrolling with mouse or up-down keys doesn't work. This is broken for all boxes at the bottom. 
Is it a problem on the UI library? In that case I'll make an issue there if you can tell me which repo.

See below. 
![SS 2021-03-11T18 40 21](https://user-images.githubusercontent.com/11729541/110830485-8d782300-8299-11eb-9839-a72bec3c7986.gif)

IMO they should also have higher weight when layout-ing so they're not such a small part of graph.

It would be best UX wise to be able to maximise both graph or the boxes at the bottom for further inspection.

**Comment by nakabonne** [comment]
@lordlycastle Thank you for your reporting! I couldn't reproduce it honestly, and it may be caused by [mum4k/termdash](https://github.com/mum4k/termdash). Could you report to them?

**Comment by lordlycastle** [comment]
@nakabonne Thanks for checking. I will double check it not my terminal emulator iTerm then make issue on termdash.

**Comment by thekvs** [comment]
Is there any workaround for this issue? Having the same issue on Ubuntu 22.04.
